/* Generated By:JavaCC: Do not edit this line. MyParserConstants.java */
package edu.curtin.saed.assignment1;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SIZE = 5;
  /** RegularExpression Id. */
  int START = 6;
  /** RegularExpression Id. */
  int GOAL = 7;
  /** RegularExpression Id. */
  int ITEM = 8;
  /** RegularExpression Id. */
  int AT = 9;
  /** RegularExpression Id. */
  int MESSAGE = 10;
  /** RegularExpression Id. */
  int LPAREN = 11;
  /** RegularExpression Id. */
  int RPAREN = 12;
  /** RegularExpression Id. */
  int LBRACE = 13;
  /** RegularExpression Id. */
  int RBRACE = 14;
  /** RegularExpression Id. */
  int COMMA = 15;
  /** RegularExpression Id. */
  int STRING_LITERAL = 16;
  /** RegularExpression Id. */
  int NUMBER = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"size\"",
    "\"start\"",
    "\"goal\"",
    "\"item\"",
    "\"at\"",
    "\"message\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "<STRING_LITERAL>",
    "<NUMBER>",
  };

}
